
FROM python:3.10-slim

RUN apt-get update && apt-get install -y --no-install-recommends build-essential && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

# Artefacts
COPY model.keras /app/model.keras
COPY tokenizer.json /app/tokenizer.json
COPY labels.txt /app/labels.txt
COPY preprocess.py /app/preprocess.py
COPY app.py /app/app.py

EXPOSE 8080
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8080"]
